#!/bin/bash

ORIGIN_DIR=$PWD

if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

if [[ $1 == "stop" ]]
then
    /etc/init.d/openvpn stop
    exit
fi

shopt -s nullglob
cd /etc/openvpn/pia

REGIONS=(*.ovpn)
INDEX=0

for f in "${REGIONS[@]}"; do
  echo $INDEX'. '${REGIONS[INDEX]}
  INDEX=$(( INDEX + 1))
done

read SELECTION

echo ${REGIONS[$SELECTION]}

cp "${REGIONS[$SELECTION]}" ../openvpn.conf
cd ..

echo "auth-nocache" >> openvpn.conf
echo "auth-user-pass login.conf" >> openvpn.conf

rc-service openvpn restart

cd $ORIGIN_DIR
